modified runme to fail.

diff --git a/runme b/runme
--- a/runme
+++ b/runme
@@ -1,2 +1,4 @@
-echo "SUCCESS!"
-exit 0
+#echo "SUCCESS!"
+#exit 0
+echo "FAIL"
+exit 1
