runme -> fail

diff --git a/runme b/runme
--- a/runme
+++ b/runme
@@ -1,4 +1,4 @@
-echo "SUCCESS!"
-exit 0
-#echo "FAIL"
-#exit 1
+#echo "SUCCESS!"
+#exit 0
+echo "FAIL"
+exit 1
